### ISSUE TITLE
[Node.js Bootcamp] Project 0: Proxy Server - Ready For Review

### ISSUE THREAD

**Issue by dorangao** [dorangao/node.js-bootcamp#1]
My app is complete. 
The app location is https://github.com/dorangao/node.js-bootcamp/tree/master/proxy-server
/cc @codepathreview and @codepath

**Comment by codepathreview** [comment]
Looks good! Hope you found this first project useful as a brief introduction or review of Node.js.

This was intended in part to give you a flavor for the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the bootcamp starts.

The next step is to continue working on extensions to your Node.js server. We will be confirming with you soon if you are going to be a part of the first Node.js bootcamp at Walmart Labs once we determine the location (Sunnyvale or San Bruno). Please email us at nodejs@codepath.com if you have any questions!

**Comment by dorangao** [comment]
Thanks for comments. I completed the optional features and some extra ones.
/cc @codepathreview and @codepath
[done] Optional: The --exec argument proxies stdin/stdout to/from the destination program
[done] Optional: The --loglevel argument sets the logging chattiness
[done] Optional: display different color for differt log lelel message
[done] Optional: Supports HTTPS
[done] Optional: Usage display
[done] extra: Support change the server log level via client request in run time.
